services:
  mysql_db:
    container_name: mysql_db
    image: mysql:9.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_db_data1:/var/lib/mysql
      - ./bd_biblioteca_mysql.sql:/docker-entrypoint-initdb.d/bd_biblioteca_mysql.sql

  phpmyadmin_db:
    container_name: phpmyadmin_db
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql_db
    ports:
      - "82:80"
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
  
  postgres_db:
    container_name: postgres_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: biblioteca
    ports:
      - "5434:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - ./bd_biblioteca_postgres.sql:/docker-entrypoint-initdb.d/bd_biblioteca_postgres.sql
  
  pgadmin_db:
    container_name: pgadmin_db
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "83:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin


volumes:
  mysql_db_data1:
  postgres_db_data: